export const MENTORS_LOADING = 'MENTORS_LOADING';
export const MENTORS_FAILED = 'MENTORS_FAILED';
export const ADD_MENTORS = 'ADD_MENTORS';

export const REQUESTS_LOADING ='REQUESTS_LOADING';
export const ADD_REQUESTS = 'ADD_REQUESTS';
export const REQUESTS_FAILED = 'REQUESTS_FAILED';
